### ISSUE TITLE
Don't forget react.rocks :)

### ISSUE THREAD

**Issue by winkler1** [giantelk/learn-reactjs#1]
Don't think it was around when you wrote this...but has lots of examples. Including http://react.rocks/tag/Beginner

**Comment by giantelk** [comment]
Thanks, I added a like to main react.rocks page.

**Comment by giantelk** [comment]
Thanks, I also added a link to your page:
https://github.com/winkler1/awesome-react

On Sun, Jan 18, 2015 at 7:24 AM, Jeff Winkler notifications@github.com
wrote:

> Don't think it was around when you wrote this...but has lots of examples.
> Including http://react.rocks/tag/Beginner
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/giantelk/learn-reactjs/issues/1.

## 

Cheers,
_Flying Horse Dancing_

**Comment by winkler1** [comment]
Thanks! That was just a fork of awesome-react though. Here's the real/current/maintained one -- https://github.com/enaqx/awesome-react

**Comment by giantelk** [comment]
Fixed thanks.
