### ISSUE TITLE
awesome-react link 404 page not found

### ISSUE THREAD

**Issue by frankhale** [giantelk/learn-reactjs#2]
The link: https://github.com/winkler1/awesome-react in the "Way More ReactJS resources" section returns a HTTP 404 page not found when clicked.

**Comment by winkler1** [comment]
yes that was just a branch I had. Link should be to https://github.com/enaqx/awesome-react.

Also, you might want to link to react.rocks - visual examples with code :)

**Comment by frankhale** [comment]
Thanks for the information!

**Comment by giantelk** [comment]
Fixed (delayed response) thanks for the comments.
